language: scala
sudo: false
jdk:
- oraclejdk8

script:
- sbt ";+ test"

addons:
  apt:
    packages:
    - oracle-java8-installer
env:
  global:
  - secure: UTzvRwqeIYINxxZ3qcCsaPJhm5dS2s2dbUG4JMqaVMDhtrSjdNDsW092bpUeSJWQ3Qs+84HkC78qMO61AebLfbVc9IteExKxhWOv+QCOTqt73gnoUer0COma7+GHg3yQWdTY79QwhBy2Jroh3g6penOaOE5dALGeWV15OLfEdtMs5Pg6y0RX8dhoc3Z5Rcj+k1upockZuet9w9hUqEWdMdQ6wDobhrZiKA7TNwNBf6gXUxh0vIpQWLhgGqYkHLz9vGEM5CrpdvJIDkqZGzunXLkX5ny1fwX+MsiVcbruU6nTfRFxK7UJ3uo+2jiH5vW7qF0SyQjBEnvvr8kBWnkM6owe31kPNsXo47HKorDA4fg1ubIZSjBLDsiDPCWugGKBhi1YYvI5CpTvQ1QCQ6D7P5MxLKRBTm/vcsndsmUCXIQohwJBn9Z7137GhioZMqa30aiFTqPZhtNP7SQIIWOgArUeRGdvZwNKMpl+w6gJDE+GLvMjnQp13YUQEdoNfU8cPaexGydAOvnFBtWShyp/w3rQIblxV1nlr/9dnOhe5wQ4BHEvgqekALz+lHumuesoYtzi6nZEiBzsEJgEmXpZLN/Fr43PmumGaU/X2LBlLkGbWp3dUSmEL3rhcxt44t34iJ/r8++goAqdoOfvxNBHjIo7ng/xRTp2SxcgW0ivOxY=
  - secure: HuRwFiWjEU7g8BZRJWmsU7ZJ0ChV4SrM3eG/gnt8MqyfVO3WwCdaa1Q66LICJf074XX+9+EEChT3ym3jOEOLj1S1z2cGAz1y9TDw5L9/IomMbeu7oJXZBy77qJVakO+5by1KlPNe0XlAzaA5CRhnEiIGVo9DgQabWxcooOawbmy7fJ4m+/yB2Pjz9tkWNe5dx5u1LkIobS4GJ6penW34OGKfNc8dirWkaSCWDgtqc5Q5Cr/unl6SKssjZC3pCoxXeg5RTdCHkVqtd8KnZdoBMNtLoJ9rl2l/Nv8aB+X1n22p6C26NEiXexBhCX/VvP7F4P8oN8jaLP33ONmfrvW5w/gOOK4fRCbK6QsYb0X+2FS+S7ACPvOkWeVPFyd0i1PDNxTFO3oJxuyBJfZyxVPnWfLuRtewWR1vzSuMX86sbxW3yy+xkAN6hjwyk8JTYUf+ICBT/puw6iNj5UCA4lyyYhXVRklN4/XLy6hw5Nqvjd3MjHpSkXp1cPSqUYEqrX7sjR9Wq7p65n9P5X6RswnDw+9QQmFRTmdarvnDKNEwvDF6S2AuGcTCJIjOfXzWJ8565Ippi5D3RfuZZHonvATIfoi9HbdxLnbhS2KWKdrmIX5awMspRA+rdLQjfozsrU+/KVhNkVg16T4xQv7Uyg+LLTE2xcWosrLWhf/CwB4m7xU=

after_success:
  - >
    test "${TRAVIS_PULL_REQUEST}" = 'false' &&
    test "${TRAVIS_BRANCH}" = 'release' &&
    sh "$TRAVIS_BUILD_DIR/.travis.credentials.sh" &&
    sbt ';+publish'

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    recipients:
      - secure: "e567pZmW8L8OE3+FkdzJdrTCYY2rnDB4gsEOUcu+J5WpianGhsrvnuw9lTdDj6ETtqIPMYNWCQZRdN9xp/nl/J+4MJkOkmN7mSwu9ZO0UOnwlBBVUc2X0pT7lf25EUOXprs/BYnpTOluk5RKmWUum5ytbCu9DDl+YGoDGkwCidunwXIpw3qPnBwsVkUgIemZc68jQqnZeXji3cjaOHXxnu3EKcOlPTkR/bnuIhCRNILe1NPW+Q8PJtDbX8u71aDv+TgUF30F4K3Rmm/9yye4kHdydFE6hTe0v4Xv3n+KNriWDvGya7en84nPUoerc7ws4FNryep88tYTD0Zoh4PQMwUV51ZZ/C4g65DWWaIgyaz1PbvJMtH5fstRMLveZKnJJbifs9KXPhoz020IJgZdcasQcpkQm0cep2o2GpN4P0KxgrI3wCYWq9859t0eg48gNa45UtLTWRZPeBTUy7ipX+U7miaXkemXKiKd0nBnwy1s7mWWlbi5unwzo6HZVx04YuZ55uqNQWXANePKFCyyVzRosPn8TOdnh/fLhv10flWZ9yeEZg7KpAOBVkq9/1Uw9ve3N6OXab9JXljyoOndXwU61JQ4XC/hoMzhqF3abOa4y6VDH2LULrsEMOigrzUvWUK7jFAAlgtPjdwzpMmzZKL3ICJlbjhmXJXBXNAGUtE="
      - secure: "L+LogCiW03C/i9slPVZVY1U1Yo3o5SMSI/8pANqEdD0hght1IGAXhQ835l1TcA5yu+BlLbFKQlZOCKCckJBhU/D1qvrSdj1S0nvoxIBj3AaAkbMNIDvXtWOkIjymZSVpoySsz+5wMnW2euNS3ykNAoK8uuFXUC5cXz+Vo19HXC2LY3XKdDVq0HYjOYyyPTaKRXPtYDq50XBQs7UDOOo19DQxY1JNupA2B/2q5XvXMBQaAZVnlsw+OqOOqy1KItwteOg1MrIXRgsE66ovwBS7CvWmE9oFzIhhBvnfof9ZY7ua8KVTlo/FwdBBmvzzD1Ed4UsU/RJeuDnlvAlKRfgYClUjyqrw/iG/BShVVUcba9vmtx+N8E9PgsWnAyLDFnr9Ve1dtlCwCGn08illvTIZPehpd/8C+5uxI0uMZol5pWhT7VvmraQNl2zuxmqArO0Pp0gYj/w8OsCA9uuig5ia6KrCvbM3/rr996qjb9h1NMfzE1uU7RwI7Ewt+SO8R23nyhEFI5E3XQN3LTL81LLEn/IaQqyqvhRLATDqcSeiscIv0Etaw1VNlmPylcnEMT/56AvL5Z861no/sYwN7gWNNqybuU0ImVR6/sBBgS1G7wwkVNWC91hUHcyLsrXkcPYrwiepPMLYRVgWC8MTRu7ZB4EjVK5yh9lpl3Gx9zkAonw="
    on_success: always
